AccountProfile/urls.py
from django.urls import path
from . import views

app_name = "AccountProfile"

urlpatterns = [
    path('', views.login_view, name="login_view"),
    path('register', views.register_view, name="register_view"),
]

Home/urls.py
from django.urls import path
from django.views.generic import TemplateView
from . import views

app_name = 'Home'

urlpatterns = [
    path('', views.home_page, name="home_page"),
    path('contact/', views.contact_page, name="contact_page"),
    path('about/', views.about_page, name="about_page"),
    path('products/<slug:slug>/', views.product_detail, name="product_detail"),
    path('template/', TemplateView.as_view(template_name='template.html'), name="template"),
    path('templaty/', TemplateView.as_view(template_name='template_check.html'), name="templaty"),
]

VahidStore/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("Home.urls")),
    path('accounts/', include("AccountProfile.urls")),
]

if settings.DEBUG:
    urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns = urlpatterns + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

AccountProfile/models.py
from django.db import models

## Create your models here.
#class UserAccount(models.Model):
#    username = models.CharField(max_length=99)
#    first_name = models.CharField(max_length=99)
#    last_name = models.CharField(max_length=99, blank=True, null=True)
#    email_adress = models.EmailField()
#    active_account = models.BooleanField(default=False,)
#    date_joined = models.DateTimeField(auto_now_add=True)
#    last_login_time = models.DateField()
    

Home/models.py
from django.db import models
from django.utils.text import slugify
from .utils import generate_unique_slug

# Create your models here.
class Category(models.Model):
    title = models.CharField(max_length=99)

    def __str__(self):
        return self.title

class Product(models.Model):
    title = models.CharField(max_length=180)
    slug = models.SlugField(unique=True, blank=True, null=True)
    price = models.DecimalField(max_digits=10, decimal_places=0, default=0, null=True)
    time_added = models.DateTimeField(auto_now=True)
    image = models.ImageField(upload_to='products/', null=True, blank=True)
    category = models.ManyToManyField(Category,)
    description = models.TextField()

    def __str__(self):
        return self.title
    
    def save(self, *args, **kwargs):
        if self.slug:  # edit
            if slugify(self.title) != self.slug:
                self.slug = generate_unique_slug(Product, self.title)
        else:  # create
            self.slug = generate_unique_slug(Product, self.title)
        super(Product, self).save(*args, **kwargs)
    
class BackgrounFigure(models.Model):
    title_1 = models.CharField(max_length=60)
    title_2 = models.CharField(max_length=60)
    image = models.ImageField(upload_to='background/')

    def __str__(self):
        return self.title_1

Home/forms.py
from django import forms

## write form classes here
class ContactForm(forms.Form):
    your_name = forms.CharField(max_length=180, widget=forms.TextInput(attrs={
        "classs": "form-control", "placeholder": "Your Full Name",
    }))
    email = forms.EmailField(widget=forms.EmailInput(attrs={
        "classs": "form-control", "placeholder": "emailadress@example.com",
    }))
    content = forms.CharField(widget=forms.Textarea(attrs={
        "classs": "form-control", "placeholder": "Please add your content here",
    }))

AccountProfile/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm

# Create your views here.
def login_view(request):
    context = {'message': ''}
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request, username=username, password=password)
        print(username, password)   
        if user is not None:
            message = "Welcome back Sir"
            login(request, user)
            return redirect('/admin')
        else:
            context['message'] = "Username or Password is Wrong!"     
    print(context)  
    return render(request, "account/login_page.html", context)

def register_view(request):
    form = UserCreationForm(request.POST or None)
    if form.is_valid():
        user_obj = form.save()
        return redirect("/accounts/")
    context = {"form": form}
    return render(request, "account/register_page.html", context)

Home/views.py
from django.shortcuts import render, get_object_or_404
from .models import Product, Category, BackgrounFigure
from .forms import ContactForm

# Create your views here.

def home_page(request):
    queryset = Product.objects.exclude(image='').exclude(image=None)
    background = BackgrounFigure.objects.all()
    context = {
        "products": queryset, "background": background,
    }
    return render(request, 'home/home.html', context)

def product_detail(request, slug):
    product = get_object_or_404(Product, slug=slug)
    context = {
        'product': product,
    }
    return render(request, "home/product_detail.html", context)

def contact_page(request):
    contact_form = ContactForm(request.POST or None)
    context = {
        "contact_form": contact_form,
    }
    return render(request, 'home/contact.html', context)

def about_page(request):
    
    context = {

    }
    return render(request, 'home/about.html', context)

Home/templates/home/about.html
{% extends "base.html" %}
{% block content %}
<h4 class="text-center"> About Page </h4>
{% endblock content %}

Home/templates/home/contact.html
{% extends "base.html" %}
{% block content %}
<h4 class="text-center"> Contact Page </h4>
<div class="container-fluid">
    <div class="row">
        <div class="col-sm-6 col-12">
            <form method="post">
                {% csrf_token %}
                <div class="col-md-5">
                    {{ contact_form }}
                    <button type="submit" class="btn btn-primary">Submit</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock content %}

Home/templates/home/home.html
{% extends "base.html" %}
{% block content %}
<div id="carouselExampleFade" class="carousel carousel-dark container-fluid slide carousel-fade w-75">
    <div class="carousel-inner">
        <div class="carousel-item active">
            <img src="{{ background.0.image.url }}" class="d-block w-100" alt="Vahid Joon1">
        </div>
        <div class="carousel-item">
            <img src="{{ background.1.image.url }}" class="d-block w-100" alt="Vahid Joon2">
        </div>
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleFade" data-bs-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="visually-hidden">Next</span>
    </button>
</div>

<h4 class="text-center"> Home Sweety home </h4>
<h6 class="text-center"> Vahid is here </h6>
<h6 class="text-center"> Money is Coming to Vahid </h6>
<div class="row">
    {% for product in products %}
    <div class="col-md-4">
        <div class="card" style="width: 18rem; height: 25rem;">
            <div class="aspect-ratio-box">
                <img src="{{ product.image.url }}" class="card-img-top" alt="{{ product.title }}">
            </div>
            <div class="card-body">
                <a href="{% url 'Home:product_detail' product.slug %}">
                    <h5 class="card-title">{{ product.title }}</h5>
                </a>
                <p class="card-text">Price: ${{ product.price }}</p>
            </div>
        </div>
    </div>
    {% endfor %}
</div>

{% endblock content %}

Home/templates/home/product_detail.html
{% extends "base.html" %}
{% block content %}
<div>
    <h5> Product: </h5>
    <p> {{ product.title }} </p>
    <h5> Category: </h5>
    <p> {{ product.category }} </p>
    <h5> Price: </h5>
    <p> {{ product.price }} </p>
    <h5> Description: </h5>
    <p> {{ product.description }} </p>
    <img src="{{ product.image.url }}" style="height: 40rcap; ">
</div>



{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Vahid Store </title>
</head>
<body>
  <div class="">
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="#">Vahid Logo</a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Home:home_page' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home:contact_page' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home:about_page' %}">About</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      <h4> {{ home }} <h4>
      {% block content %}
      {% endblock %}
    </div>
  </div>
</body>
</html>

templates/old_base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
    
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title> Vahid Store </title>
</head>
<body>
  <div class="">
    <nav class="navbar navbar-expand-lg bg-light">
      <div class="container-fluid">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01" aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
          <a class="navbar-brand" href="#">Vahid Logo</a>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a class="nav-link active" aria-current="page" href="{% url 'Home:home_page' %}">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home:contact_page' %}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'Home:about_page' %}">About</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'AccountProfile:login_view' %}">Login</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="container">
      <h4> {{ home }} <h4>
      {% block content %}
      {% endblock %}
    </div>
  </div>
<script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
</body>
</html>

templates/template.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Template Test</title>
    <link rel="stylesheet" href="{% static 'bootstrap/css/bootstrap.min.css' %}">
  </head>
  <body>
    <nav class="navbar navbar-expand-sm navbar-light bg-light">
      <div class="container">
        <a class="navbar-brand" href="{% url "Home:home_page"%}">
          <img src="{% static "logo.png" %}" alt="" width="30" height="30" class="d-inline-block align-text-top">
          Vahidoo
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
          <ul class="navbar-nav">
            <li class="nav-item">
              <a class="nav-link" href="{% url "Home:contact_page"%}">Contact</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "AccountProfile:login_view"%}">Login</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url "Home:about_page"%}">About</a>
            </li>
          </ul>
        </div>
      </div>
    </nav>
    <div class="container">

    </div>
    
    
    
    
    
    
    
    
    <h1>Testy Template </h1>
    <h2>Testy Template </h2>
    <h3>Testy Template </h3>
    <h4>Testy Template </h4>
    <h5>Testy Template </h5>
    <h6>Testy Template </h6>
    <p>Testy Template </p>
  <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.min.js' %}"></script>
  </body>
</html>

templates/template_check.html
{% extends "base.html" %}

{% block content %}
    <h1>Testy Template </h1>
    <h2>Testy Template </h2>
    <h3>Testy Template </h3>
    <h4>Testy Template </h4>
    <h5>Testy Template </h5>
    <h6>Testy Template </h6>
    <p>Testy Template </p>
{% endblock content %}